"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fibonacci = [1, 2]
add = 0
while add <= 4000000:
    l = len(fibonacci)
    add = fibonacci[l-1] + fibonacci[l-2]
    if add <= 4000000:
        fibonacci.append(add)
print(fibonacci)
resultado = 0
l = len(fibonacci)
for i in range(0,l):
    if fibonacci[i]%2 == 0:
        resultado = resultado + fibonacci[i]
print(resultado)
