"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math
def isPrime(n):
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True

def prime_factors(n):
    i = 2
    factors = []
    while i * i <= n:
        if n%i != 0:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def number_divisors(n):
    primeFactors = prime_factors(n)
    l = len(primeFactors)
    cantidad = []
    counter = 2
    for i in range(0,l-1):
        if primeFactors[i] == primeFactors[i+1]:
            counter += 1
        else:
            cantidad.append(counter)
            counter = 2
    cantidad.append(counter)
    l = len(cantidad)
    resultado = 1
    for i in range(0,l):
        resultado = resultado * cantidad[i]
    return resultado

contador = 1
num = 1
while number_divisors(num) <= 500:
    contador = contador + 1
    num = num + contador
    print(num)

